-- Database
use FlightBookingSystem

-- ques 1: Identify Passengers with Pending Reservations and Passengers with age more than 40 years.
Select p.PassengerId,p.FirstName,p.LastName, DATEDIFF(YEAR,p.DateOfBirth,GETDATE()) as age
		from Passenger p join Reservation r on p.PassengerId=r.PassengerId
		where DATEDIFF(YEAR,p.DateOfBirth,GETDATE())>40 and r.BookingStatus='Pending';

-- ques 2: a) Search the database of the ticketing system for matching character strings by last name of passenger. 
--                  Results should be sorted with most recent issued ticket first.
Create procedure SearchPassengerByLastName
	@LastName nvarchar(50)
as 
begin
Select p.PassengerId, p.Firstname,p.Lastname,t.TicketId,t.Issuedate  
	from Passenger p join Reservation r on p.PassengerId=r.PassengerId
	join Ticket t on r.ReservationId=t.ReservationId 
	where p.Lastname like '%'+@LastName+'%'
	order by t.Issuedate desc
end

exec SearchPassengerByLastName 'son'

-- b) Return a full list of passengers and his/her specific meal requirement in business class who has a reservation today 
--      (i.e., the system date when the query is run)
Create function GetBusinessClassPassengersToday()
returns table
as
return
	Select p.PassengerId,p.Firstname,p.Lastname,p.Mealpreference,r.Bookingdate,t.class 
		from Passenger p join Reservation r on p.PassengerId=r.PassengerId
		join Ticket t on r.ReservationId=t.ReservationId 
		where t.class='Business' and r.Bookingdate=cast(GETDATE() AS DATE);

select* from GetBusinessClassPassengersToday()

-- c) Insert a new employee into the database.
Create procedure InsertNewEmployee
	@EmployeeName nvarchar(100),
	@EmployeeEmail nvarchar(100),
	@EmployeeRole nvarchar(20)
as 
begin
	Insert into Employee(EmployeeName, EmployeeEmail, EmployeeRole)
    values (@EmployeeName, @EmployeeEmail, @EmployeeRole)
end;

EXEC InsertNewEmployee 'George Martin', 'george.martin@email.com', 'Ticketing Staff';
Select* from Employee

-- d) Update the details for a passenger that has booked a flight before.
Create procedure UpdatePassengerDetails
    @PassengerId int,
    @FirstName nvarchar(50),
    @LastName nvarchar(50),
    @Email nvarchar(50),
    @MealPreference nvarchar(15)
as
begin
    if exists (Select 1 from Reservation where PassengerId = @PassengerId)
    begin
        update Passenger
        set FirstName = @FirstName,
            LastName = @LastName,
            Email = @Email,
            MealPreference = @MealPreference
        where PassengerId = @PassengerId;
    end
    else
	begin
        print 'Passenger has no reservations and cannot be updated.';
    end
end;

EXEC UpdatePassengerDetails 
    @PassengerId = 11,
    @FirstName = 'Robert',
    @LastName = 'White',
    @Email = 'new.robert@email.com',
    @MealPreference = 'Vegetarian';

-- ques 3: 
/*  The ticketing system wants to be able to view all e-boarding numbers Issued by a Specific
Employee showing the overall revenue generated by that employee on a particular
flight. It should include details of the fare, additional baggage fees, upgraded meal or
preferred seat. You should create a view containing all the required information  */

--Create view EmployeeTicketRevenue as
Create View EmployeeTicketRevenue as
Select e.EmployeeId,e.EmployeeName,t.TicketId as EboardingNumber, f.flightId,f.FlightNumber,
	sum(t.Fare) as TotalTicketFare ,sum( ISNULL(b.BaggageFee,0)) as BaggageFee,sum( ISNULL(a.TotalAdditionalFare,0) )as TotalAdditionalFare,
	sum((t.Fare + ISNULL(a.TotalAdditionalFare, 0))) AS TotalRevenuePerTicket 
	from Ticket t  join Reservation r on t.ReservationId=r.ReservationId join  Flight f on r.FlightId = f.FlightId
	join Employee e on t.EmployeeId = e.EmployeeId
	left join Baggage b on t.TicketId = b.TicketId
	left join AdditionalServices a on t.TicketId = a.TicketId
	group by E.EmployeeId, E.EmployeeName, F.FlightId, F.FlightNumber,t.ticketId

Select * from EmployeeTicketRevenue
	where EmployeeId = 3 and FlightNumber = 'FL789';

-- Ques 4: Create a trigger so that the current seat allotment of a passenger automatically updates to reserved when the ticket is issued.
Alter table Ticket add SeatStatus nvarchar(10) 
default 'Available' check (SeatStatus in ('Available', 'Reserved'));
update Ticket set SeatStatus='Reserved'
select * from Ticket

Create trigger UpdateSeatStatusOnIssue
on Ticket
after insert
as
begin
    update T
    set SeatStatus = 'Reserved'
    from Ticket T
    inner join inserted i on T.TicketId = i.TicketId
    inner join Reservation R on i.ReservationId = R.ReservationId
    where R.BookingStatus = 'Confirmed';
end;


-- Ques 5: You should provide a function or view which allows the ticketing system to
--                identify the total number of baggage’s (which are checkedin) made on a specified date for a specific flight.
Create view BaggageSummary as
Select r.FlightId,t.IssueDate, count(b.BaggageId) as TotalBaggageCheckedIn
	from Baggage b inner join Ticket t on b.TicketId=t.TicketId inner join Reservation r on t.ReservationId=r.ReservationId
	where b.BaggageStatus='Checked-In' group by r.FlightId,t.IssueDate

SELECT * FROM BaggageSummary
WHERE FlightId = 2 AND IssueDate = '2025-06-03';

-- Ques 6: If there are any other database objects such as views, stored procedures, user-defined
/*functions, or triggers which you think would be relevant to the airport scenario given
the brief above, you will obtain higher marks for providing these along with an
explanation of their functionality. */

-- query 1:( To automatically reject baggage entries that exceed the 20kg free allowance without appropriate baggage fee in Baggage table.)
Create trigger PreventOverweightBaggageWithoutFee
on Baggage
instead of insert
as
begin
    If exists (
        select 1 
        from inserted 
        where BaggageWeight > 20 AND BaggageFee < (BaggageWeight - 20) * 100
    )
    begin
        raiserror('Overweight baggage must include appropriate additional fee.', 16, 1)
        rollback transaction
        return
    end

    -- If all good, insert the baggage
    Insert into Baggage (TicketId, BaggageWeight, BaggageStatus, BaggageFee)
    Select TicketId, BaggageWeight, BaggageStatus, BaggageFee
    from inserted
end;

-- query 2(Find passengers who spent more than £1000 (fare + services) in total.)
Select 
    P.PNR,
    P.FirstName,
    P.LastName,
    SUM(T.Fare + ISNULL(A.TotalAdditionalFare, 0)) as TotalSpent
from Passenger P
join Reservation R on P.PassengerId = R.PassengerId
join Ticket T on R.ReservationId = T.ReservationId
left join AdditionalServices A on T.TicketId = A.TicketId
group by P.PNR, P.FirstName, P.LastName
having SUM(T.Fare + ISNULL(A.TotalAdditionalFare, 0)) > 1000;